### ISSUE TITLE
About the SR result

### ISSUE THREAD

**Issue by beingnothing** [yutxie/MARS#3]
Hi, I'm grateful that you released the code of your ICLR 2021 paper, I have just run your code and the experiment settings are the same as your code shows. But the results were not good as that of your paper, especially the gsk3b and jnk3 scores are usually lower than 0.5 so the SR is always far too lower than that of your results. Can you figure out what is wrong with my experiment?  Thanks.

**Comment by yutxie** [comment]
Hi, thanks for your interest in our work! 

Are you trying to reproduce the results of the GSK3b+JNK3+QED+SA setting? Can you help me to check whether the model is being training during the sampling?

I reviewed my released code, and it seems that I've forgotten to add the "--train" option in default arguments. I also revised some other default options that conflict with the setting which produces the results in the paper. 

Can you help me to redownload the code and run `python -m MARS.main --train --run_dir runs/RUN_DIR`? Thanks!
